environment:
  access_token:
    secure: oWn3mv+wxoVw9NT6nh6+VVM2KzoTnnX3qbhjVn2R+yyxBCmBFvoHF57jnMw69E21
  access_token_ks:
    secure: BqtNr3JlK85SZdqNKOm6yqxWQZlLD6fFsSOOZjLSsw6yAt90iDt7ZnhfbSvCk5CCNm3zmnOaUgYBk3fpCoLKM5XY8Sm2Zmy5dc2W8Z8VAMI=
  github_access_token_appveyor:
    secure: 9Z+iJbAt3SVWp4/F34xGQ1iDUf1XIdshovPwK3wMQf8B8wI+o2XyFsg8NmJlsYkl
  github_user_email_appveyor: appveyor@ksware.de
  github_user_name_appveyor: Appveyor-KsWare

version: 0.1.{build}
branches:
  only:
  - Master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: \Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
init:
- cmd: echo Configuration file: "appveyor.yml"'
before_build:
- echo "--- before build script ---"
- nuget restore src
build:
  project: src\KsWare.MSBuildTargets\KsWare.MSBuildTargets.csproj
  publish_nuget: true
  verbosity: normal
before_package:
- echo --- before packaging script ---
after_build:
- echo --- after build script ---
- cmd: FOR /F " usebackq tokens=*" %%f IN (`dir %temp% /B /S^|find ".nupkg"`) DO @set TEMPPACK=%%~dpf
- echo nuget pack %APPVEYOR_BUILD_FOLDER%\src\KsWare.MSBuildTargets\KsWare.MSBuildTargets.csproj -properties "Configuration=%configuration%;Platform=AnyCPU" -OutputDirectory "%TEMPPACK:~0,-1%" -Version %appveyor_build_version% -tool
- nuget pack %APPVEYOR_BUILD_FOLDER%\src\KsWare.MSBuildTargets\KsWare.MSBuildTargets.csproj -properties "Configuration=%configuration%;Platform=AnyCPU" -OutputDirectory "%TEMPPACK:~0,-1%" -Version %appveyor_build_version% -tool
before_deploy:
- cmd: echo "--- Before deployment script ---"
deploy:
- provider: NuGet
  api_key:
    secure: +s8U6nHVwO/TqmfVs5r8zR8OV4Gv4APhlY1HKsySnnceRp0auneX/TSqKQZx7G50
  skip_symbols: true
  on:
    branch: Master
after_deploy:
- ps: echo "--- After deployment script --- "
on_success:
- echo "`n--- On build success script --- "
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\\.git-credentials" "https://$($env:github_access_token_appveyor):x-oauth-basic@github.com`n"
- git config --global user.email "%github_user_email_appveyor%"
- git config --global user.name "%github_user_name_appveyor%"
- git checkout master
- git commit -a -m "[skip ci] increment version %appveyor_build_version%"
- git push
on_failure:
- cmd: 'echo --- On build error script --- '
on_finish:
- cmd: 'echo --- On build finish script --- '